#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

IS_MASTER=true
if [ -f /mnt/var/lib/info/instance.json ]; then
  IS_MASTER=`jq .isMaster /mnt/var/lib/info/instance.json`
fi
[ "$IS_MASTER" = "false" ] && exit 0

echo "Starting HDFS early..."
sudo service hadoop-hdfs-namenode start
sudo service hadoop-hdfs-datanode start

echo "Waiting for port 9000 to be listening..."
for i in {1..30}; do
  sleep 1s;
  echo "Attempt #$i";
  nc -z ${HOSTNAME} 9000 && break;
done

echo "Creating directories in HDFS..."
# Storage plugin writable workspace for user data like views and CTAS
hdfs dfs -mkdir -p /user/drill
# For query profiles and maybe other logs written by Drill, exposed as a readonly storage plugin workspace
hdfs dfs -mkdir -p /var/log/drill
# For Drill's internal spilling/spooling, not exposed in a storage plugin
hdfs dfs -mkdir -p /tmp/drill
