#!/bin/sh

# Copyright (C) 2015 Commerce Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

IS_MASTER=true
if [ -f /mnt/var/lib/info/instance.json ]; then
  IS_MASTER=`jq .isMaster /mnt/var/lib/info/instance.json`
fi
[ "$IS_MASTER" = "false" ] && exit 0

echo "Stopping early HDFS in case it has been reconfigured..."
sudo service hadoop-hdfs-namenode stop
sudo service hadoop-hdfs-datanode stop

# Let service-nanny start it back up.
